INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK01','Reliance Industries',2940,2940 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Reliance Industries');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK02','HDFC Bank',1850,1850 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='HDFC Bank');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK03','ICICI Bank',1840,1840 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='ICICI Bank');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK04','Infosys',1620,1620 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Infosys');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK05','TCS',3480,3480 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='TCS');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK06','Bharti Airtel',1710,1710 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Bharti Airtel');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK07','Larsen & Toubro',3700,3700 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Larsen & Toubro');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK08','Axis Bank',1180,1180 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Axis Bank');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK09','Kotak Mahindra Bank',2050,2050 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Kotak Mahindra Bank');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK10','SBI',820,820 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='SBI');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK11','Bajaj Finance',9800,9800 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Bajaj Finance');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK12','Maruti Suzuki',12500,12500 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Maruti Suzuki');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK13','Mahindra & Mahindra',2970,2970 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Mahindra & Mahindra');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK14','Titan',3600,3600 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Titan');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK15','Asian Paints',2520,2520 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Asian Paints');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK16','UltraTech Cement',12500,12500 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='UltraTech Cement');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK17','Sun Pharma',1700,1700 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Sun Pharma');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK18','NTPC',370,370 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='NTPC');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK19','Power Grid',345,345 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Power Grid');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK20','Tata Motors',980,980 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Tata Motors');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK21','Adani Ports',1450,1450 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Adani Ports');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK22','Adani Enterprises',2500,2500 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Adani Enterprises');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK23','JSW Steel',950,950 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='JSW Steel');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK24','HCL Technologies',1680,1680 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='HCL Technologies');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK25','Tech Mahindra',1700,1700 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Tech Mahindra');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK26','Nestlé India',2450,2450 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Nestlé India');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK27','Hindustan Unilever',2650,2650 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Hindustan Unilever');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK28','ITC',465,465 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='ITC');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK29','Wipro',320,320 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Wipro');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK30','ONGC',240,240 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='ONGC');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK31','Coal India',550,550 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Coal India');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK32','Bajaj Auto',7600,7600 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Bajaj Auto');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK33','Cipla',1200,1200 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Cipla');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK34','Dr. Reddy''s',6200,6200 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Dr. Reddy''s');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK35','IndusInd Bank',1450,1450 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='IndusInd Bank');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK36','Tata Steel',175,175 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Tata Steel');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK37','Eicher Motors',6200,6200 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Eicher Motors');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK38','Apollo Hospitals',6700,6700 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Apollo Hospitals');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK39','Trent',7200,7200 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Trent');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK40','BEL',300,300 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='BEL');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK41','Bharat Forge',1400,1400 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Bharat Forge');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK42','DLF',950,950 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='DLF');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK43','Grasim',1110,1110 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Grasim');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK44','Divi''s Laboratories',3150,3150 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Divi''s Laboratories');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK45','Siemens India',2350,2350 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Siemens India');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK46','Pidilite Industries',1200,1200 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Pidilite Industries');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK47','Shriram Finance',650,650 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Shriram Finance');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK48','Hindalco',1400,1400 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Hindalco');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK49','Zomato (Eternal)',210,210 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='Zomato (Eternal)');
INSERT INTO stocks (symbol,name,price,previous_price) SELECT 'STK50','InterGlobe Aviation',4800,4800 WHERE NOT EXISTS (SELECT 1 FROM stocks WHERE name='InterGlobe Aviation');
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,1 FROM stocks WHERE name='Reliance Industries' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=1);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,2 FROM stocks WHERE name='HDFC Bank' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=2);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,3 FROM stocks WHERE name='ICICI Bank' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=3);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,4 FROM stocks WHERE name='Infosys' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=4);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,5 FROM stocks WHERE name='TCS' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=5);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,6 FROM stocks WHERE name='Bharti Airtel' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=6);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,7 FROM stocks WHERE name='Larsen & Toubro' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=7);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,8 FROM stocks WHERE name='Axis Bank' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=8);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,9 FROM stocks WHERE name='Kotak Mahindra Bank' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=9);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,10 FROM stocks WHERE name='SBI' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=10);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,11 FROM stocks WHERE name='Bajaj Finance' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=11);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,12 FROM stocks WHERE name='Maruti Suzuki' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=12);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,13 FROM stocks WHERE name='Mahindra & Mahindra' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=13);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,14 FROM stocks WHERE name='Titan' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=14);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,15 FROM stocks WHERE name='Asian Paints' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=15);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,16 FROM stocks WHERE name='UltraTech Cement' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=16);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,17 FROM stocks WHERE name='Sun Pharma' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=17);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,18 FROM stocks WHERE name='NTPC' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=18);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,19 FROM stocks WHERE name='Power Grid' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=19);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,20 FROM stocks WHERE name='Tata Motors' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=20);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,21 FROM stocks WHERE name='Adani Ports' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=21);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,22 FROM stocks WHERE name='Adani Enterprises' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=22);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,23 FROM stocks WHERE name='JSW Steel' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=23);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,24 FROM stocks WHERE name='HCL Technologies' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=24);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,25 FROM stocks WHERE name='Tech Mahindra' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=25);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,26 FROM stocks WHERE name='Nestlé India' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=26);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,27 FROM stocks WHERE name='Hindustan Unilever' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=27);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,28 FROM stocks WHERE name='ITC' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=28);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,29 FROM stocks WHERE name='Wipro' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=29);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,30 FROM stocks WHERE name='ONGC' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=30);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,31 FROM stocks WHERE name='Coal India' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=31);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,32 FROM stocks WHERE name='Bajaj Auto' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=32);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,33 FROM stocks WHERE name='Cipla' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=33);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,34 FROM stocks WHERE name='Dr. Reddy''s' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=34);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,35 FROM stocks WHERE name='IndusInd Bank' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=35);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,36 FROM stocks WHERE name='Tata Steel' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=36);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,37 FROM stocks WHERE name='Eicher Motors' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=37);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,38 FROM stocks WHERE name='Apollo Hospitals' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=38);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,39 FROM stocks WHERE name='Trent' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=39);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,40 FROM stocks WHERE name='BEL' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=40);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,41 FROM stocks WHERE name='Bharat Forge' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=41);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,42 FROM stocks WHERE name='DLF' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=42);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,43 FROM stocks WHERE name='Grasim' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=43);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,44 FROM stocks WHERE name='Divi''s Laboratories' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=44);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,45 FROM stocks WHERE name='Siemens India' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=45);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,46 FROM stocks WHERE name='Pidilite Industries' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=46);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,47 FROM stocks WHERE name='Shriram Finance' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=47);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,48 FROM stocks WHERE name='Hindalco' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=48);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,49 FROM stocks WHERE name='Zomato (Eternal)' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=49);
INSERT INTO stock_catalog(stock_id,company_number) SELECT id,50 FROM stocks WHERE name='InterGlobe Aviation' AND NOT EXISTS (SELECT 1 FROM stock_catalog WHERE company_number=50);