CREATE TABLE IF NOT EXISTS event_control (
 id BIGINT PRIMARY KEY DEFAULT 1,
 event_name TEXT NOT NULL DEFAULT 'JAIN SECURITIES EXCHANGE',
 status TEXT NOT NULL DEFAULT 'NOT_STARTED',
 created_at TIMESTAMP NOT NULL DEFAULT now(),
 updated_at TIMESTAMP NOT NULL DEFAULT now(),
 CHECK (id=1),
 CHECK (status IN ('NOT_STARTED','LIVE','SETTLEMENT_ONLY','CLOSED','FINALIZED'))
)