-- JAIN STOCK EXCHANGE — exact customer stock catalog
-- Source: Stock List(3).docx supplied for this project.
INSERT INTO public.assets(symbol,name,type,base_price_paise,current_price_paise,previous_price_paise,lot_size,display_order,is_active)
VALUES ('WIPRO','Wipro','LISTED_STOCK',32000,32000,32000,50,37,true)
ON CONFLICT(symbol) DO UPDATE SET name='Wipro',type='LISTED_STOCK',is_active=true;
UPDATE public.assets SET display_order=CASE symbol
WHEN 'RELIANCE' THEN 10 WHEN 'HDFCBANK' THEN 11 WHEN 'ICICIBANK' THEN 12 WHEN 'INFY' THEN 13 WHEN 'TCS' THEN 14
WHEN 'BHARTIARTL' THEN 15 WHEN 'LT' THEN 16 WHEN 'AXISBANK' THEN 17 WHEN 'KOTAKBANK' THEN 18 WHEN 'SBIN' THEN 19
WHEN 'BAJFINANCE' THEN 20 WHEN 'MARUTI' THEN 21 WHEN 'M_M' THEN 22 WHEN 'TITAN' THEN 23 WHEN 'ASIANPAINT' THEN 24
WHEN 'ULTRACEMCO' THEN 25 WHEN 'SUNPHARMA' THEN 26 WHEN 'NTPC' THEN 27 WHEN 'POWERGRID' THEN 28 WHEN 'TATAMOTORS' THEN 29
WHEN 'ADANIPORTS' THEN 30 WHEN 'ADANIENT' THEN 31 WHEN 'JSWSTEEL' THEN 32 WHEN 'HCLTECH' THEN 33 WHEN 'TECHM' THEN 34
WHEN 'NESTLEIND' THEN 35 WHEN 'HINDUNILVR' THEN 36 WHEN 'WIPRO' THEN 37 WHEN 'ITC' THEN 38 WHEN 'ONGC' THEN 39
WHEN 'COALINDIA' THEN 40 WHEN 'BAJAJ-AUTO' THEN 41 WHEN 'CIPLA' THEN 42 WHEN 'DRREDDY' THEN 43 WHEN 'INDUSINDBK' THEN 44
WHEN 'TATASTEEL' THEN 45 WHEN 'EICHERMOT' THEN 46 WHEN 'APOLLOHOSP' THEN 47 WHEN 'TRENT' THEN 48 WHEN 'BEL' THEN 49
WHEN 'BHARATFORG' THEN 50 WHEN 'DLF' THEN 51 WHEN 'GRASIM' THEN 52 WHEN 'DIVISLAB' THEN 53 WHEN 'SIEMENS' THEN 54
WHEN 'PIDILITE' THEN 55 WHEN 'SHRIRAMFIN' THEN 56 WHEN 'HINDALCO' THEN 57 WHEN 'ETERNAL' THEN 58 WHEN 'INDIGO' THEN 59
ELSE display_order END,
name=CASE WHEN symbol='NESTLEIND' THEN 'Nestlé India' ELSE name END
WHERE type='LISTED_STOCK';